// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrX_aMLcyZxiF4xf8RrZXb79I9xUvSsxw',
    appId: '1:415467037952:web:9b7959ec56c6c8bd2f7fe5',
    messagingSenderId: '415467037952',
    projectId: 'itsago-2654e',
    authDomain: 'itsago-2654e.firebaseapp.com',
    storageBucket: 'itsago-2654e.firebasestorage.app',
    measurementId: 'G-9PFW8GCRLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbLNm2lOelk6zQmdYwIp5mKoMCTx12DA',
    appId: '1:415467037952:android:1f62192ef612f3312f7fe5',
    messagingSenderId: '415467037952',
    projectId: 'itsago-2654e',
    storageBucket: 'itsago-2654e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9YqVd49W6gLajmYotdYPhVd0nSP3N40',
    appId: '1:415467037952:ios:84208b463d42a91f2f7fe5',
    messagingSenderId: '415467037952',
    projectId: 'itsago-2654e',
    storageBucket: 'itsago-2654e.firebasestorage.app',
    androidClientId: '415467037952-5ubv4i5c3l4vq4t7drb5k2f31mfbg728.apps.googleusercontent.com',
    iosClientId: '415467037952-kl348b383pptjfklmoslheccguov717s.apps.googleusercontent.com',
    iosBundleId: 'com.itsago.interviewai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB9YqVd49W6gLajmYotdYPhVd0nSP3N40',
    appId: '1:415467037952:ios:5b46c6d0578d54172f7fe5',
    messagingSenderId: '415467037952',
    projectId: 'itsago-2654e',
    storageBucket: 'itsago-2654e.firebasestorage.app',
    androidClientId: '415467037952-5ubv4i5c3l4vq4t7drb5k2f31mfbg728.apps.googleusercontent.com',
    iosClientId: '415467037952-lmb2t04bl7bco16e3ad3vf1p2js6jgha.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrX_aMLcyZxiF4xf8RrZXb79I9xUvSsxw',
    appId: '1:415467037952:web:9cdd691926fca6242f7fe5',
    messagingSenderId: '415467037952',
    projectId: 'itsago-2654e',
    authDomain: 'itsago-2654e.firebaseapp.com',
    storageBucket: 'itsago-2654e.firebasestorage.app',
    measurementId: 'G-0XCQ4QFTPC',
  );

}